# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: enabled
dist: trusty
cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'

    packages:
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev

matrix:
    include:
        - os: linux
          r: release
          dist: xenial # 16.04
          env:
          - R_CODECOV=true
          - BUILD_NAME=xenial_release
        - os: linux
          r: devel
          dist: xenial
        - os: linux
          r: oldrel
          dist: trusty
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
          env:
          - R_CODECOV=true
          - BUILD_NAME=osx_release

          #- os: osx
          #r: devel
          #before_install: ''
          #disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
