# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: enabled

cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
#      - libprotobuf-dev
#      - protobuf-compiler
#      - libv8-3.14-dev
#      - libjq-dev
#      - libjson-c-dev
#      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - gdal-bin
      - pkg-config
  homebrew:
    packages:
      - pkg-config
      - gdal
      - netcdf
      - sqlite
      - curl
      - libgit2
      - udunits
    update: true

matrix:
    include:
        - os: linux
          r: release
          dist: trusty
          env:
           - BUILD_NAME=trusty_release
           - R_CODECOV=true
        - os: linux
          r: devel
          dist: trusty
        - os: linux
          r: oldrel
          dist: trusty
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: false
          env:
           - BUILD_NAME=osx_release
           - R_CODECOV=true
          #- os: osx
          #r: devel
          #before_install: ''
          #disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
